### PR TITLE
update url to display detail of vulnerabilities

### PR DESCRIPTION
**Pull request by kamroy**

### CODE REVIEW

**Review by Gamedevboras — APPROVED** [review]

**Comment by Gamedevboras** [comment]
I was planning on doing the exact same PR.

**Review by Vad1mo — APPROVED** [review]

**Comment by Vad1mo** [comment]
should we use (kee) tags or digsest? @kamroy @Gamedevboras @locomoco28 ?

**Comment by Gamedevboras** [comment]
Using digest can make it more applicable to other users.  But I also think there should be a config that says: useTag  = true/false. Need to test some more.

**Comment by locomoco28** [comment]
I added the artifact digest to the response in my PR on the backend plugin so we can merge this PR to use the digest in the frontend.

Imo it's not that important to be able to switch between tag name and digest. The harbor UI shows you the artifact with all available tag names anyways.

<details>
<summary>Example screenshots from Harbor (you can also see, I used project ID and project name, both work)</summary>

image

image

image

</details>

**Pull request merged**
